name: Echo Secrets and Variables
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_VAR: "This is not a secret."

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Echo environment variable
        run: echo "My environment variable is $MY_VAR"

      - name: Echo GitHub secret
        run: echo "My GitHub secret is ${{ secrets.MY_GITHUB_SECRET }}"
